site_name: Pok√©mon Automation
site_url: https://pokemonautomation.github.io
repo_url: https://github.com/PokemonAutomation/ComputerControl
repo_name: PokemonAutomation/ComputerControl
# If true (default), use_directory_urls convert every md file not named index.md, <path>/<filename>.md, into 
# <path/<filename>/index.html so the website viewers can use the link <path>/<filename> to view the page,
# hiding .html extension. But this messes up the image asset links in those md files. In order to view images
# both on the website and in the Github repo pages, we set use_directory_urls to false so eavery md file
# is converted into <path>/<filename>.html. This preserves the folder hierarchy when converted to website. 
use_directory_urls: false

theme:
  logo: assets/original_logo_no_background.png  # logo shown on webpage
  favicon: assets/logo.png  # brower tab icon
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - toc.follow
    - toc.integrate
    - search.suggest
    - search.highlight
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

# Defines the navigation tab bar on PC / dropdown menu on mobile
nav:
  - Home: index.md
  - Getting Started: 
      - SetupGuide/index.md
      - Controllers: SetupGuide/Controllers
  - Programs: 
      - Programs/index.md
      - NintendoSwitch: Programs/NintendoSwitch
      - PokemonBDSP: Programs/PokemonBDSP
      - PokemonHome: Programs/PokemonHome
      - PokemonLGPE: Programs/PokemonLGPE
      - PokemonLZA: Programs/PokemonLZA
      - PokemonSV: Programs/PokemonSV
      - PokemonSwSh: Programs/PokemonSwSh
      - ZeldaTotK: Programs/ZeldaTotK
      - ML: Programs/ML
  - Controllers: ControllerList.md
  - Discord Integration:
      - Overview: DiscordIntegration/index.md
      - Discord Bot: DiscordIntegration/DiscordBot.md
      - Discord Webhooks: DiscordIntegration/DiscordWebhooks.md
  - Developer:
      - Overview: Developer/index.md
      - Knowledge Requirement: Developer/Knowledge.md
      - How to Use Github: Developer/Git.md
      - Tutorial Button Script: Developer/TutorialMC.md
      - Tutorial Home Sorter: Developer/TutorialCC.md
      - Development Topics: Developer

plugins:
  # Create social cards for link preview
  # https://squidfunk.github.io/mkdocs-material/setup/setting-up-social-cards/
  # This only works if "site_url" is set in mkdocs.yml.
  - social
  - search
  - include_dir_to_nav

# extensions
markdown_extensions:
  - toc:
      permalink: true

# Exclude unused docs from being generated into webpages
# https://www.mkdocs.org/user-guide/configuration/#exclude_docs
exclude_docs: |
  /z_TestHome.md
  /z_TemplateProgramPage.md
